version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
nuget:
  disable_publish_on_pr: true
build_script:
  - cmd: dotnet restore -f netstandard2.0
  - cmd: dotnet build -f netstandard2.0
  #- cmd: dotnet test .\test\Webenable.Extensions.Configuration.GoogleCloud.Tests
  - cmd: dotnet pack .\src\Webenable.Extensions.Configuration.GoogleCloud -c Release -o .\artifacts -f netstandard2.0
test: off
branches:
  only:
    - master
init:
  - git config --global core.autocrlf input
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CI: true
artifacts:
- path: .\src\Webenable.Extensions.Configuration.GoogleCloud\artifacts\**\*.nupkg
  name: NuGet